blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/RapidAI/TableStructureRec/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding ProcessLaTeXFormulaTools Docs
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/RapidAI/TableStructureRec/discussions/new?category=feature-requests
    about: Please vote for and post new feature ideas in the community forum
  - name: ğŸ“– Documentation
    url: https://rapidai.github.io/TableStructureRec/docs/
    about: A great place to find instructions and answers about RapidOCR.